services:
  api:
    build: .
    container_name: olympic-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  token-shop:
    build: ./token-shop
    container_name: token-shop
    ports:
      - "8001:8001"

  cache:
    build: ./cache
    container_name: cache
    ports:
      - "8002:8002"

  rate-limiter:
    build: ./rate-limiter
    container_name: rate-limiter
    ports:
      - "8003:8003"

  logger:
    build: ./logger
    container_name: logger
    ports:
      - "8004:8004"
    volumes:
      - ./logger/logs:/app/logs